services:
  db:
    image: postgres:14
    container_name: pulseiq_postgres_dev
    environment:
      POSTGRES_DB: pulseiq_db
      POSTGRES_USER: pulseiq_user
      POSTGRES_PASSWORD: cse408
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
      - ./backend/init-schema.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
    networks:
      - pulseiq-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pulseiq_user", "-d", "pulseiq_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: pulseiq_backend_dev
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8085:8085"
    networks:
      - pulseiq-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pulseiq_db?currentSchema=pulseiq
      - SPRING_DATASOURCE_USERNAME=pulseiq_user
      - SPRING_DATASOURCE_PASSWORD=cse408
      - JWT_SECRET=w7Zz8g3kS0Hjb3YzF5k3jI2pK8VrTPCB2qLm+XhQz6M=
      - FIREBASE_ENABLED=true
    volumes:
      # Mount source code for hot reload (optional)
      - ./backend/src:/app/src:ro
      - ./backend/pom.xml:/app/pom.xml:ro
    env_file:
      - .env
    # Override CMD to use the faster development mode
    command: ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-Dspring.profiles.active=dev"]

  frontend:
    build: ./frontend
    container_name: pulseiq_frontend_dev
    depends_on:
      - app
    ports:
      - "8080:8080"
    networks:
      - pulseiq-network
    environment:
      - VITE_BACKEND_URL=http://localhost:8085
      # Add your Firebase config here if needed for development
    volumes:
      # Mount source code for hot reload
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

volumes:
  pgdata_dev:

networks:
  pulseiq-network:
